//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoinPrice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IranArzTbl
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Nemad { get; set; }
        public decimal Price { get; set; }
        public System.DateTime Updated { get; set; }
    }
}
